# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Outputting
permalink: /posts/:categories/:year:month:day.html
timezone: Asia/Shanghai
paginate: 25
paginate_path: "./p:num/"
excerpt_separator: <!-- more -->

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Original Plan
author: Quadrifolium
#email: 
description: > # this means to ignore newlines until "baseurl:"
  This site translates the posts of Sina Weibo accounts of and related to Original Plan.
baseurl: "/originalplan" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: QuadrifoliumW
github_username:  Quadrifolium

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
  - jekyll-paginate
  - jekyll-coffeescript
exclude:
  - Gemfile
  - Gemfile.lock
